{{- if .Values.token.auth.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lats.fullname" . }}-authsecret
  labels:
    app: {{ template "lats.name" . }}
    chart: {{ template "lats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.token.auth.secret | b64enc | quote }}
{{- end }}