{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lats.fullname" . }}-redispwd
  labels:
    app: {{ template "lats.name" . }}
    chart: {{ template "lats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
{{- end }}