apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lats.fullname" . }}-secrets
  labels:
    app: {{ template "lats.name" . }}
    chart: {{ template "lats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  auth: {{ .Values.token.auth.secret | b64enc | quote }}
  access: {{ .Values.token.access.secret | b64enc | quote }}
  verify: {{ .Values.token.verify.secret | b64enc | quote }}
  admin: {{ .Values.token.admin.secret | b64enc | quote }}