apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ template "lats.fullname" . }}-social-auth
  labels:
    app: {{ template "lats.name" . }}
    chart: {{ template "lats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  {{- range .Values.social.hosts }}
  - {{ . }}
  {{- end }}
  #- graph.facebook.com
  #- www.googleapis.com
  #- accounts.google.com

  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS